name: PromoteDockerImage

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "main"
  workflow_dispatch:

jobs:
  sonarCloud:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Sonar Cloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: ${{ github.workspace }}/src
          args: >
            -Dsonar.organization=vladoiliev02
            -Dsonar.projectKey=vladoiliev02_mdp-task-1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  snyk:
    runs-on: ubuntu-latest
    steps: 
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  push_image:
    needs: 
      - sonarCloud
      - snyk
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
        
      - name: Build docker image
        run: docker image build -t ${{ vars.DOCKERHUB_USER }}/py-app:latest .
      
      - name: Push docker image to registry
        run: |
          docker login --username ${{ vars.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_PASSWORD }}
          docker push ${{ vars.DOCKERHUB_USER }}/py-app:latest
          docker logout
