name: PromoteDockerImage

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "main"
  workflow_dispatch:

jobs:
  push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
        
      - name: Build docker image
        run: docker image build -t ${{ vars.DOCKERHUB_USER }}/py-app:latest .
      
      - name: Push docker image to registry
        run: |
          docker login --username ${{ vars.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_PASSWORD }}
          docker push ${{ vars.DOCKERHUB_USER }}/py-app:latest
          docker logout
