name: SonarCloudOnPR

on:
  pull_request:
    types:
      - opened

jobs:
  sonarCloud:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Sonar Cloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: ${{ github.workspace }}/src
          args: >
            -Dsonar.organization=vladoiliev02
            -Dsonar.projectKey=vladoiliev02_mdp-task-1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
